[package]
name = "rust-lib-example"
version = "0.1.0"
edition = "2024"
description = "excrises for rust"


[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }





